version: '3'
services:
  karaf:
    image: marem/karaf-sandbox:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - 1099:1099
      - 8101:8101
      - 4444:4444
      - 8181:8181
    networks:
      - karafsandbox
networks:
  karafsandbox:
