version: '3'
services:
  karaf:
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 1099:1099
      - 8101:8101
      - 4444:4444
      - 8181:8181
    networks:
      - karaf-sandbox
networks:
  karaf-sandbox: