version: '3.2'
services:
  karaf:
    build: .
    volumes:
      - type: volume
        source: m2repo
        target: /root/.m2
    ports:
      - 1099:1099
      - 8101:8101
      - 4444:4444
      - 8181:8181
    networks:
      - sandbox
networks:
  sandbox:
volumes:
  m2repo: